export async function GET(request: Request) {
  const endpoint = new URL("/api/ipl", request.url).toString();
  const script = `javascript:(async()=>{const endpoint=${JSON.stringify(endpoint)};const wait=(ms)=>new Promise(r=>setTimeout(r,ms));const list=document.querySelector("#leadersList");if(!list)return alert("Leaderboard not found");const names={"Team RJ":"Raviteja Jakkani","Pratik Falcon11":"Pratik Gurnani","Rahul XI":"Rahul Sharma","WATAPI11":"Rishikesh Shinde","RKs STALLIONS":"Ravi Kiran Guthula","Ghost Riders":"Rushabh Shah","VATVAGHOOL XI":"Vijay Swami","Aditya Raut":"Aditya Raut","PKs 11":"Pankaj Konde","Nilesh Birajdar":"Nilesh Birajdar"};const leaders=Array.from(list.querySelectorAll("li")).map((el)=>{const rank=parseInt(el.querySelector(".m11c-matchCount")?.innerText||"999",10);const rawName=el.querySelector(".m11c-tbl__cell--name span")?.innerText.trim()||"";const name=names[rawName]||rawName;const points=parseFloat((el.querySelector(".m11c-tbl__cell--pts span")?.innerText||"0").replace(/,/g,""));return{rank,name,points,element:el}}).filter(x=>x.name&&!Number.isNaN(x.rank)&&!Number.isNaN(x.points)).sort((a,b)=>a.rank-b.rank);for(const leader of leaders){leader.element.scrollIntoView({behavior:"smooth",block:"center"});leader.element.click();await wait(1300);leader.lastMatchPoints=parseFloat(document.querySelector(".m11c-pitch__fix-rgt em")?.innerText.trim()||"0")||0;const overall=Array.from(document.querySelectorAll("li.swiper-slide")).find(el=>el.textContent.trim().toUpperCase()==="OVERALL");overall&&overall.click();await wait(1300);const head=document.querySelector(".m11c-transfer__head");if(head){head.querySelectorAll("span").forEach((span)=>{const text=span.textContent.trim();if(text.includes("Transfers Left"))leader.transfersLeft=parseInt(span.querySelector("em")?.innerText.trim().split("/")[0]||"",10);if(text.includes("Boosters used"))leader.boostersUsed=span.querySelector("em")?.innerText.trim()||"";});}}const payload={updatedAt:new Date().toISOString(),leaders:leaders.map(({element,...leader})=>leader)};const res=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!res.ok){const text=await res.text();throw new Error(text||"Upload failed");}alert("IPL dashboard updated: "+leaders.length+" teams");})().catch(err=>alert("Dashboard update failed: "+err.message));`;

  return new Response(script, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "no-store",
    },
  });
}
